env_files:
  github_token: ~/.config/goreleaser/github_token

builds:
- skip: true

archives:
- format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs: []
