//! Protobuf types for the Substreams KV sink.
//!
//! Generated by the `buf.build/anthropics/buffa` plugin; run `buf generate` to regenerate.

macro_rules! include_buffa {
    ($package:literal) => {
        include!(concat!($package, ".mod.rs"));
    };
}

pub mod sf {
    pub mod substreams {
        pub mod sink {
            pub mod kv {
                pub mod v1 {
                    include_buffa!("sf.substreams.sink.kv.v1");

                    /// Alias matching the name `prost` generated for `KVOperations`.
                    #[deprecated(
                        since = "0.2.0",
                        note = "Use KVOperations instead, which matches the Protobuf message name; this alias will be removed in future versions."
                    )]
                    pub type KvOperations = KVOperations;

                    /// Alias matching the name `prost` generated for `KVOperation`.
                    #[deprecated(
                        since = "0.2.0",
                        note = "Use KVOperation instead, which matches the Protobuf message name; this alias will be removed in future versions."
                    )]
                    pub type KvOperation = KVOperation;
                }
            }
        }
    }
}
