// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/sink/kv/v1/kv.proto

#[derive(Clone, Debug, Default)]
pub struct KVOperationsView<'a> {
    /// Field 1: `operations`
    pub operations: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::KVOperationView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for KVOperationsView<'a> {
    type Owned = super::super::KVOperations;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::KVOperationView,
                    >(),
                )?;
                view.operations
                    .push(
                        <super::super::__buffa::view::KVOperationView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::KVOperations, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::KVOperations, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::KVOperations {
            operations: self
                .operations
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for KVOperationsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.operations {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.operations {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for KVOperationsView<'a> {
    const PACKAGE: &'static str = "sf.substreams.sink.kv.v1";
    const NAME: &'static str = "KVOperations";
    const FULL_NAME: &'static str = "sf.substreams.sink.kv.v1.KVOperations";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.kv.v1.KVOperations";
}
::buffa::impl_default_view_instance!(KVOperationsView);
::buffa::impl_view_reborrow!(KVOperationsView);
/** Self-contained, `'static` owned view of a `KVOperations` message.

 Wraps [`::buffa::OwnedView`]`<`[`KVOperationsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`KVOperationsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct KVOperationsOwnedView(::buffa::OwnedView<KVOperationsView<'static>>);
impl KVOperationsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            KVOperationsOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            KVOperationsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::KVOperations,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            KVOperationsOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`KVOperationsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &KVOperationsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::KVOperations {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `operations`
    #[must_use]
    pub fn operations(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::KVOperationView<'_>> {
        &self.0.reborrow().operations
    }
}
impl ::core::convert::From<::buffa::OwnedView<KVOperationsView<'static>>>
for KVOperationsOwnedView {
    fn from(inner: ::buffa::OwnedView<KVOperationsView<'static>>) -> Self {
        KVOperationsOwnedView(inner)
    }
}
impl ::core::convert::From<KVOperationsOwnedView>
for ::buffa::OwnedView<KVOperationsView<'static>> {
    fn from(wrapper: KVOperationsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<KVOperationsView<'static>>>
for KVOperationsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<KVOperationsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::KVOperations {
    type View<'a> = KVOperationsView<'a>;
    type ViewHandle = KVOperationsOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct KVOperationView<'a> {
    /// Field 1: `key`
    pub key: &'a str,
    /// Field 2: `value`
    pub value: &'a [u8],
    /// Field 3: `ordinal`
    pub ordinal: u64,
    /// Field 4: `type`
    pub r#type: ::buffa::EnumValue<super::super::kv_operation::Type>,
}
impl<'a> ::buffa::MessageView<'a> for KVOperationView<'a> {
    type Owned = super::super::KVOperation;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.key = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.value = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.ordinal = ::buffa::types::decode_uint64(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.r#type = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(&mut cur)?,
                );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::KVOperation, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::KVOperation, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::KVOperation {
            key: self.key.to_string(),
            value: (self.value).to_vec(),
            ordinal: self.ordinal,
            r#type: self.r#type,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for KVOperationView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.key.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.key) as u64;
        }
        if !self.value.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.value) as u64;
        }
        if self.ordinal != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.ordinal) as u64;
        }
        {
            let val = self.r#type.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.key.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.key, buf);
        }
        if !self.value.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.value, buf);
        }
        if self.ordinal != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.ordinal, buf);
        }
        {
            let val = self.r#type.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(4u32, val, buf);
            }
        }
    }
}
impl<'a> ::buffa::MessageName for KVOperationView<'a> {
    const PACKAGE: &'static str = "sf.substreams.sink.kv.v1";
    const NAME: &'static str = "KVOperation";
    const FULL_NAME: &'static str = "sf.substreams.sink.kv.v1.KVOperation";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.kv.v1.KVOperation";
}
::buffa::impl_default_view_instance!(KVOperationView);
::buffa::impl_view_reborrow!(KVOperationView);
/** Self-contained, `'static` owned view of a `KVOperation` message.

 Wraps [`::buffa::OwnedView`]`<`[`KVOperationView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`KVOperationView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct KVOperationOwnedView(::buffa::OwnedView<KVOperationView<'static>>);
impl KVOperationOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            KVOperationOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            KVOperationOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::KVOperation,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            KVOperationOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`KVOperationView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &KVOperationView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::KVOperation {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `key`
    #[must_use]
    pub fn key(&self) -> &'_ str {
        self.0.reborrow().key
    }
    /// Field 2: `value`
    #[must_use]
    pub fn value(&self) -> &'_ [u8] {
        self.0.reborrow().value
    }
    /// Field 3: `ordinal`
    #[must_use]
    pub fn ordinal(&self) -> u64 {
        self.0.reborrow().ordinal
    }
    /// Field 4: `type`
    #[must_use]
    pub fn r#type(&self) -> ::buffa::EnumValue<super::super::kv_operation::Type> {
        self.0.reborrow().r#type
    }
}
impl ::core::convert::From<::buffa::OwnedView<KVOperationView<'static>>>
for KVOperationOwnedView {
    fn from(inner: ::buffa::OwnedView<KVOperationView<'static>>) -> Self {
        KVOperationOwnedView(inner)
    }
}
impl ::core::convert::From<KVOperationOwnedView>
for ::buffa::OwnedView<KVOperationView<'static>> {
    fn from(wrapper: KVOperationOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<KVOperationView<'static>>>
for KVOperationOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<KVOperationView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::KVOperation {
    type View<'a> = KVOperationView<'a>;
    type ViewHandle = KVOperationOwnedView;
}
