// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.substreams.sink.kv.v1.kv.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.sink.kv.v1.kv.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.sink.kv.v1.kv.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::KVOperationsView;
#[doc(inline)]
pub use self::__buffa::view::KVOperationsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::KVOperationsLazyView;
#[doc(inline)]
pub use self::__buffa::view::KVOperationView;
#[doc(inline)]
pub use self::__buffa::view::KVOperationOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::KVOperationLazyView;
