// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/sink/kv/v1/kv.proto

#[derive(Clone, PartialEq, Default)]
pub struct KVOperations {
    /// Field 1: `operations`
    pub operations: ::buffa::alloc::vec::Vec<KVOperation>,
}
impl ::core::fmt::Debug for KVOperations {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("KVOperations").field("operations", &self.operations).finish()
    }
}
impl KVOperations {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.kv.v1.KVOperations";
}
::buffa::impl_default_instance!(KVOperations);
impl ::buffa::MessageName for KVOperations {
    const PACKAGE: &'static str = "sf.substreams.sink.kv.v1";
    const NAME: &'static str = "KVOperations";
    const FULL_NAME: &'static str = "sf.substreams.sink.kv.v1.KVOperations";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.kv.v1.KVOperations";
}
impl ::buffa::Message for KVOperations {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.operations {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.operations {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.operations.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.operations.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct KVOperation {
    /// Field 1: `key`
    pub key: ::buffa::alloc::string::String,
    /// Field 2: `value`
    pub value: ::buffa::alloc::vec::Vec<u8>,
    /// Field 3: `ordinal`
    pub ordinal: u64,
    /// Field 4: `type`
    pub r#type: ::buffa::EnumValue<kv_operation::Type>,
}
impl ::core::fmt::Debug for KVOperation {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("KVOperation")
            .field("key", &self.key)
            .field("value", &self.value)
            .field("ordinal", &self.ordinal)
            .field("type", &self.r#type)
            .finish()
    }
}
impl KVOperation {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.kv.v1.KVOperation";
}
::buffa::impl_default_instance!(KVOperation);
impl ::buffa::MessageName for KVOperation {
    const PACKAGE: &'static str = "sf.substreams.sink.kv.v1";
    const NAME: &'static str = "KVOperation";
    const FULL_NAME: &'static str = "sf.substreams.sink.kv.v1.KVOperation";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.kv.v1.KVOperation";
}
impl ::buffa::Message for KVOperation {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.key.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.key) as u64;
        }
        if !self.value.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.value) as u64;
        }
        if self.ordinal != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.ordinal) as u64;
        }
        {
            let val = self.r#type.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.key.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.key, buf);
        }
        if !self.value.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.value, buf);
        }
        if self.ordinal != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.ordinal, buf);
        }
        {
            let val = self.r#type.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(4u32, val, buf);
            }
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.key, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.value, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.ordinal = ::buffa::types::decode_uint64(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.r#type = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.key.clear();
        self.value.clear();
        self.ordinal = 0u64;
        self.r#type = ::buffa::EnumValue::from(0);
    }
}
pub mod kv_operation {
    #[allow(unused_imports)]
    use super::*;
    #[allow(non_camel_case_types)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
    #[repr(i32)]
    pub enum Type {
        /// Protobuf default should not be used, this is used so that the consume can ensure that the value was actually specified
        UNSET = 0i32,
        SET = 1i32,
        DELETE = 2i32,
    }
    impl Type {
        ///Idiomatic alias for [`Self::UNSET`]; `Debug` prints the variant name.
        #[allow(non_upper_case_globals)]
        pub const Unset: Self = Self::UNSET;
        ///Idiomatic alias for [`Self::SET`]; `Debug` prints the variant name.
        #[allow(non_upper_case_globals)]
        pub const Set: Self = Self::SET;
        ///Idiomatic alias for [`Self::DELETE`]; `Debug` prints the variant name.
        #[allow(non_upper_case_globals)]
        pub const Delete: Self = Self::DELETE;
    }
    impl ::core::default::Default for Type {
        fn default() -> Self {
            Self::UNSET
        }
    }
    impl ::buffa::Enumeration for Type {
        fn from_i32(value: i32) -> ::core::option::Option<Self> {
            match value {
                0i32 => ::core::option::Option::Some(Self::UNSET),
                1i32 => ::core::option::Option::Some(Self::SET),
                2i32 => ::core::option::Option::Some(Self::DELETE),
                _ => ::core::option::Option::None,
            }
        }
        fn to_i32(&self) -> i32 {
            *self as i32
        }
        fn proto_name(&self) -> &'static str {
            match self {
                Self::UNSET => "UNSET",
                Self::SET => "SET",
                Self::DELETE => "DELETE",
            }
        }
        fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
            match name {
                "UNSET" => ::core::option::Option::Some(Self::UNSET),
                "SET" => ::core::option::Option::Some(Self::SET),
                "DELETE" => ::core::option::Option::Some(Self::DELETE),
                _ => ::core::option::Option::None,
            }
        }
        fn values() -> &'static [Self] {
            &[Self::UNSET, Self::SET, Self::DELETE]
        }
    }
}
